This is just an example of how a params_df can look in practice and how estimagic can help to parse the parameter vector more efficiently. You don't have to understand the details of the respy model.

In [6]:
import pandas as pd
from estimagic.optimization.utilities import cov_params_to_matrix

In [7]:
params_df = pd.read_csv('kw_data_one.csv').set_index(['category', 'name'])
params_df

                                      value  fixed  lower  upper  \
category      name
delta         delta                  0.9500  False    0.7    1.0
coeffs_common return_hs_degree       0.0000  False    NaN    NaN
              return_col_degree      0.0000  False    NaN    NaN
coeffs_a      skill_price            9.2100  False    NaN    NaN
              return_schooling       0.0380  False    NaN    NaN
              exp_a                  0.0330  False    NaN    NaN
              exp_a_square          -0.0005  False    NaN    NaN
              exp_b                  0.0000  False    NaN    NaN
              exp_b_square           0.0000  False    NaN    NaN
              premium_hs             0.0000  False    NaN    NaN
              premium_col            0.0000  False    NaN    NaN
              age                    0.0000  False    NaN    NaN
              minor                  0.0000  False    NaN    NaN
              not_first              0.0000  False    NaN    NaN
              no_switch              0.0000  False    NaN    NaN
              constant               0.0000  False    NaN    NaN
              first                  0.0000  False    NaN    NaN
              switch                 0.0000  False    NaN    NaN
coeffs_b      skill_price            8.4800  False    NaN    NaN
              return_schooling       0.0700  False    NaN    NaN
              exp_a                  0.0220  False    NaN    NaN
              exp_a_square          -0.0005  False    NaN    NaN
              exp_b                  0.0670  False    NaN    NaN
              exp_b_square          -0.0010  False    NaN    NaN
              premium_hs             0.0000  False    NaN    NaN
              premium_col            0.0000  False    NaN    NaN
              age                    0.0000  False    NaN    NaN
              minor                  0.0000  False    NaN    NaN
              not_first              0.0000  False    NaN    NaN
              no_switch              0.0000  False    NaN    NaN
              constant               0.0000  False    NaN    NaN
              first                  0.0000  False    NaN    NaN
              switch                 0.0000  False    NaN    NaN
coeffs_edu    constant               0.0000  False    NaN    NaN
              value_col              0.0000  False    NaN    NaN
              value_grad             0.0000  False    NaN    NaN
              reenroll_col       -4000.0000  False    NaN    NaN
              reenroll_hs        -4000.0000  False    NaN    NaN
              age                    0.0000  False    NaN    NaN
              minor                  0.0000  False    NaN    NaN
coeffs_home   constant           17750.0000  False    NaN    NaN
              18_to_20               0.0000  False    NaN    NaN
              21_plus                0.0000  False    NaN    NaN
shocks        chol_sigma_1           0.2000  False    NaN    NaN
              chol_sigma_21          0.0000  False    NaN    NaN
              chol_sigma_2           0.2500  False    NaN    NaN
              chol_sigma_31          0.0000  False    NaN    NaN
              chol_sigma_32          0.0000  False    NaN    NaN
              chol_sigma_3        1500.0000  False    NaN    NaN
              chol_sigma_41          0.0000  False    NaN    NaN
              chol_sigma_42          0.0000  False    NaN    NaN
              chol_sigma_43          0.0000  False    NaN    NaN
              chol_sigma_4        1500.0000  False    NaN    NaN

                                                                           comment
category      name
delta         delta                                                discount factor
coeffs_common return_hs_degree        return to high school degree (non pecuniary)
              return_col_degree           return to college degree (non pecuniary)
coeffs_a      skill_price        skill rental price if the base skill endowment...
              return_schooling   linear return to an additional year of schooli...
              exp_a               return to experience, same sector, linear (wage)
              exp_a_square       return to experience, same sector, quadratic (...
              exp_b              return to experience, other civilian sector, l...
              exp_b_square       return to experience, other civilian sector, q...
              premium_hs         skill premium of having finished high school (...
              premium_col          skill premium of having finished college (wage)
              age                                         linear age effect (wage)
              minor                                 effect of being a minor (wage)
              not_first          gain of having worked in the same occupation a...
              no_switch          gain of remaining in the same occupation as pr...
              constant                                    constant (non pecuniary)
              first              reward of switching to a from other occupation...
              switch             reward of working in a for the first time (non...
coeffs_b      skill_price        skill rental price if the base skill endowment...
              return_schooling   linear return to an additional year of schooli...
              exp_a              return to experience, other civilian sector, l...
              exp_a_square       return to experience, other civilian sector, q...
              exp_b               return to experience, same sector, linear (wage)
              exp_b_square       return to experience, same sector, quadratic (...
              premium_hs         skill premium of having finished high school (...
              premium_col          skill premium of having finished college (wage)
              age                                         linear age effect (wage)
              minor                                 effect of being a minor (wage)
              not_first          gain of having worked in the same occupation a...
              no_switch          gain of remaining in the same occupation as pr...
              constant                                    constant (non pecuniary)
              first              reward of switching to a from other occupation...
              switch             reward of working in a for the first time (non...
coeffs_edu    constant           consumption value of school attendance for type 1
              value_col                               consumption value of college
              value_grad                      consumption value of graduate school
              reenroll_col                        reward for going back to college
              reenroll_hs                     reward for going back to high school
              age                                                linear age effect
              minor                                        effect of being a minor
coeffs_home   constant             mean value of non-market alternative for type 1
              18_to_20              additional value of staying home if aged 18-20
              21_plus              additional value of staying home if 21 or older
shocks        chol_sigma_1       Element 1,1 of cholesky factor of shock covari...
              chol_sigma_21      Element 2,1 of cholesky factor of shock covari...
              chol_sigma_2       Element 2,2 of cholesky factor of shock covari...
              chol_sigma_31      Element 3,1 of cholesky factor of shock covari...
              chol_sigma_32      Element 3,2 of cholesky factor of shock covari...
              chol_sigma_3       Element 3,3 of cholesky factor of shock covari...
              chol_sigma_41      Element 4,1 of cholesky factor of shock covari...
              chol_sigma_42      Element 4,2 of cholesky factor of shock covari...
              chol_sigma_43      Element 4,3 of cholesky factor of shock covari...
              chol_sigma_4       Element 4,4 of cholesky factor of shock covari...

In [8]:
constraints = [{'loc': 'shocks', 'type': 'covariance'}]

In [9]:
shock_coeffs = cov_params_to_matrix(params_df.loc['shocks', 'value'].to_numpy())

In [10]:
shock_coeffs

array([[2.0e-01, 0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 2.5e-01, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.5e+03, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 1.5e+03]])